### PR TITLE
Add Asciidoc version of text.

### PR DESCRIPTION
**Pull request by james-bostock**
As a reference, I used a scanned copy from the Internet Archive:

https://archive.org/stream/ladysusanwatson00austgoog#page/n6/mode/2up

As such, the Asciidoc version includes the preface from the scanned
copy.

Additional changes:

Capitilization of first words of each chapter.
Consistency with periods after signatures.
Consistency in formatting of signatures.

Conversion to Asciidoc revealed the following shortcomings of
Asciidoc (or of my knowledge of Asciidoc):
- Indicating that small caps should be used for a segment of text.
- Centering or right aligning text.

### CODE REVIEW

**Comment by sethwoodworth** [comment]
Asciidoc doesn't do a great job of applying specific formats to named parts of text from the syntax.  It requires setting up a particular template and css to get that desired output.  

Can you link me to an archive.org page of the aligning or small caps?  I may be able to help find something.

**Comment by sethwoodworth** [comment]
I've read over the PR.  The asciidoc looks good :+1: .
I see what you mean now about small caps and right-align.  Googling about asciidoc and small-caps came up with a [tweet](https://twitter.com/gitenberg/status/580038901810761728) about it from @GITenberg :-S.  I've filed an issue (gitenberg-dev/gitberg/issues/121).

**Comment by james-bostock** [comment]
Great! Thanks!

**Comment by sethwoodworth** [comment]
Thank you for getting this transcribed!

**Pull request merged**
